// src/components/VehicleList.vue
<template>
  <div class="row g-2">
    <template
      v-for="vehicle of vehicles"
      :key="vehicle.id"
    >
      <div class="col-4">
        <div class="card">
          <img
            :src="vehicle.photoUrl"
            class="card-img-top"
          >

          <div class="card-body">
            <router-link
              class="btn btn-link p-0 text-primary"
              :to="{name: 'garage-show', params: {id: vehicle.id}}"
            >
              {{ vehicle.model }}
            </router-link>

            <p class="card-text">
              {{ vehicle.licensePlate }}
            </p>
          </div>
        </div>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import {Vehicle} from '~/types';

defineProps<{
  vehicles: Vehicle[];
}>();
</script>

<style scoped lang="scss">
img {
  height: 12rem;
  background: $light;
}
</style>

// src/lib/components/VehicleList.svelte
<script lang="ts">
	import type { Vehicle } from '$lib/types';

	export let vehicles: Vehicle[];
</script>

<div class="row g-3">
	{#each vehicles as vehicle}
		<div class="col-4">
			<div class="card">
				<div class="card-img-top" />

				<div class="card-body">
					<a class="card-title text-primary" href="/app/vehicles?edit={vehicle.id}">
						{vehicle.model}
					</a>

					<div class="card-text">
						<small class="text-muted">{vehicle.id}</small>
					</div>
				</div>
			</div>
		</div>
	{/each}
</div>

<style lang="scss">
	.card-img-top {
		height: 10rem;
		background: $light;
		object-fit: cover;
	}
</style>
